In [ ]:
import numpy as np

In [ ]:
#1-d Array
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
print(arr1.ndim)

1


In [ ]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr2.ndim)

2


In [ ]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(arr3.ndim)

2


In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
arr4=np.ones((3,3))

In [ ]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [ ]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])

print(arr1[0])

1


In [ ]:
arr1[3]

4

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#2nd element on 1st row
arr2[0,1]

2

In [ ]:
arr2[1]

array([4, 5, 6])

In [ ]:
arr2[1,1]

5

In [ ]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr3[1:5])

[2 3 4 5]


In [ ]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[4:])

[5 6 7]


In [ ]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr5[:4])

[1 2 3 4]


In [ ]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr6[-3:-1])

[5 6]


In [ ]:
#Return every other element from index 1 to index 5:

arr7 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr7[1:5:2])

[2 4]


In [ ]:
# Shape of an Array: shape that returns a tuple with each index having the number of corresponding elements.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# NumPy Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Random Numbers
# NumPy offers the random module to work with random numbers.
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)

94


In [ ]:
# Random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.27744359518505524


In [ ]:
# Generate Random Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[24 39 39 61 45]


In [ ]:
# A 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[55 97 84 58 85]
 [15 82 46 55 14]
 [48 88 83 81 78]]


In [ ]:
# Generate a 1-D array containing 5 random floats:
from numpy import random

x = random.rand(5)

print(x)

[0.49965857 0.88585275 0.37919481 0.83195011 0.5597361 ]


In [ ]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.98446992 0.4518538  0.37472607 0.03257088 0.57348279]
 [0.72392483 0.07713902 0.96696182 0.29465208 0.68511804]
 [0.35585327 0.02154561 0.51112126 0.05048128 0.61560501]]
